source 'https://rubygems.org'

gem 'rails', '4.2.4'

gem 'activerecord-import'
gem 'bootstrap-sass'
gem 'bootswatch-rails', '>= 3.3.4'
gem 'coffee-rails', '>= 4.1.0'
gem 'devise', '>= 3.5.1'
gem 'dotenv-rails', '>= 2.0.2'
gem 'exception_notification', '>= 4.1.1'
gem 'faraday'
gem 'font-awesome-rails', '>= 4.3.0.0'
gem 'foreman'
gem 'google-analytics-rails'
gem 'hamlit'
gem 'jbuilder'
gem 'jquery-rails', '>= 4.0.4'
gem 'kaminari', '>= 0.16.3'
gem 'mysql2'
gem 'newrelic_rpm'
gem 'octokit'
gem 'omniauth', '>= 1.2.2'
gem 'omniauth-github', '>= 1.1.2'
gem 'progress_bar'
gem 'rack-user_agent', '>= 0.2.3'
gem 'redis-rails', '>= 4.0.0'
gem 'sass-rails', '>= 5.0.3'
gem 'sidekiq'
gem 'sinatra', '>= 1.4.6'
gem 'therubyracer'
gem 'uglifier'
gem 'unicorn', '>= 4.9.0'

group :development, :test do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-sidekiq'
  gem 'factory_girl'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rspec-rails', '>= 3.3.2'
  gem 'silencer', '>= 0.6.0'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'timecop'
end
